In [1]:
import pandas as pd

In [2]:
flights = pd.read_csv('flights_1%.csv')

In [3]:
flights_train = pd.read_csv('flights_train.csv')

In [4]:
flights_test = pd.read_csv('flights_test.csv')

In [7]:
flights_train.head()

,id,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,...,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name
0,121941,2019-08-25,AA,AA_CODESHARE,AA,5636,OH,N723PS,5636,11057,...,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,109932,2018-03-02,WN,WN,WN,2028,WN,N244WN,2028,13495,...,471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,63108,2019-03-06,UA,UA,UA,545,UA,N69804,545,11292,...,862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,91519,2019-10-11,DL,DL_CODESHARE,DL,3798,OO,N452SW,3798,16869,...,553,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8361,2019-09-26,UA,UA_CODESHARE,UA,5359,OO,N120SY,5359,10713,...,522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
flights.loc[63108]

fl_date                 2019-03-06
mkt_unique_carrier              UA
branded_code_share              UA
mkt_carrier                     UA
mkt_carrier_fl_num             545
op_unique_carrier               UA
tail_num                    N69804
op_carrier_fl_num              545
origin_airport_id            11292
origin                         DEN
origin_city_name        Denver, CO
dest_airport_id              12266
dest                           IAH
dest_city_name         Houston, TX
crs_dep_time                  1214
dep_time                      1233
dep_delay                       19
taxi_out                        12
wheels_off                    1245
wheels_on                     1531
taxi_in                          4
crs_arr_time                  1531
arr_time                      1535
arr_delay                        4
cancelled                        0
cancellation_code              NaN
diverted                         0
dup                              N
crs_elapsed_time               137
actual_elapsed_time            122
air_time                       106
flights                          1
distance                       862
carrier_delay                  NaN
weather_delay                  NaN
nas_delay                      NaN
security_delay                 NaN
late_aircraft_delay            NaN
first_dep_time                 NaN
total_add_gtime                NaN
longest_add_gtime              NaN
no_name                        NaN
Name: 63108, dtype: object